steps:
  - name: hashicorp/packer:1.6.2
    args:
      - "validate"
      - "base.json"
  - name: hashicorp/packer:1.6.2
    args:
      - "build"
      - "-var"
      - "tag_name=$TAG_NAME"
      - "base.json"
